name: Test Project
on: [push, workflow_dispatch]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js & dependencies
        uses: ./.github/actions/cached-deps

      - name: Run tests
        working-directory: ./second-action
        run: npm test
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js & dependencies
        uses: ./.github/actions/cached-deps

      - name: Build project
        working-directory: ./second-action
        run: npm run build

      - name: Deploy to server
        run: echo "Deploying to server..."
